server:
  port: 9010

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379

---

spring:
  config:
    activate:
      on-profile: test
  spring:
    data:
      redis:
        host: 127.0.0.1
        port: 63790